### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by luca-moser** [ibp-org/testbed#1]

**Comment by luca-moser** [comment]
123

**Comment by luca-moser** [comment]
123

**Comment by luca-moser** [comment]
123

**Comment by luca-moser** [comment]
123

**Comment by luca-moser** [comment]
release bounty @luca-moser

**Comment by luca-moser** [comment]
release bounty to @luca-moser

**Comment by luca-moser** [comment]
release bounty @luca-moser

**Comment by luca-moser** [comment]
release bounty to @luca-moser

**Comment by luca-moser** [comment]
release bounty to @luca-moser

**Comment by luca-moser** [comment]
WJZQRCWYKKXYS9TJBDPVCHZCNDVEUD9CWPKWRWGZC9OJXDP9BF9GWABRXRMVGCXWZZNYRSXRHKHCWATYYYKIWAYWPB

**Comment by luca-moser** [comment]
WJZQRCWYKKXYS9TJBDPVCHZCNDVEUD9CWPKWRWGZC9OJXDP9BF9GWABRXRMVGCXWZZNYRSXRHKHCWATYYYKIWAYWPB

**Comment by enut-test** [comment]
This issue has been linked with the bounty platform.  
Help rising the incentive to solve this issue by sending iota tokens to the following address:
[QQDGWEDT9GBVSBCOGGRXETXYZUYYOPOHJTGMMBNHOIYRGEIWKSHAAZ9HEIOKF9WP9F9QHTTHP9KYQZFBAZYRDVNAUC](https://thetangle.org/address/QQDGWEDT9GBVSBCOGGRXETXYZUYYOPOHJTGMMBNHOIYRGEIWKSHAAZ9HEIOKF9WP9F9QHTTHP9KYQZFBAZYRDVNAUC)

> Please note that the tokens you send to the address can not be recovered

Important:
**If you move this repository make sure to await for the bounty platform to synchronize the repository state before releasing a bounty.**

#### Releasing the bounty (as a repository admin)
Release the bounty by issuing following comment:
`release bounty to @<bounty_receiver_name>`

#### Receiving the bounty (as the issue solver)
Simply create a comment with your IOTA address (+checksum, must be 90 chars long!) to which to receive the tokens to after the above 'release comment' has been posted.

**Comment by enut-test** [comment]
The bounty associated with this issue has been deleted from the bounty platform, therefore
the bounty is no longer active.
