### ISSUE TITLE
Implements a high performance caching algorithm

### ISSUE THREAD

**Issue by luca-moser** [ibp-org/testbed#3]
I want to get some monez for fixing this awesome issue.

**Comment by luca-moser** [comment]
release bounty to @luca-moser

**Comment by luca-moser** [comment]
FSACIVWTSSUKBMDWFBJCYYPHSSDTHEQVRWR9OPQFFECY9THMQHRXBSAOATBUGKLDBBNEWRHGGTPLGYNSDRLEFAQCCY

**Comment by enut-test** [comment]
This issue has been linked with the bounty platform.  
Help rising the incentive to solve this issue by sending iota tokens to the following address:
[V9AMDUJHJPVFYQOD9LQZAJMLNGUOGMWAEPETUITZFRMCTCXIPRUMAYCEFFFDOCNAZKBAZCJBXYXHLMENCRPLMSDYMC](https://thetangle.org/address/V9AMDUJHJPVFYQOD9LQZAJMLNGUOGMWAEPETUITZFRMCTCXIPRUMAYCEFFFDOCNAZKBAZCJBXYXHLMENCRPLMSDYMC)

> Please note that the tokens you send to the address can not be recovered

Important:
**If you move this repository make sure to await for the bounty platform to synchronize the repository state before releasing a bounty.**

#### Releasing the bounty (as a repository admin)
Release the bounty by issuing following comment:
`release bounty to @<bounty_receiver_name>`

#### Receiving the bounty (as the issue solver)
Simply create a comment with your IOTA address (+checksum, must be 90 chars long!) to which to receive the tokens to after the above 'release comment' has been posted.
